public class secondProgrammingTest {
   
   //Set this boolean to true to mute the logs
   public static boolean mute = false;
   
   //Implement the Measurement class
   //Allow for the class initalization to accept a variable that is assigned to the instance variable inches
   //Create a getter and setter method for the inches instance variable
   //Create a method getFeet(), that will convert the inches instance variable into feet and return it
   //IMPORTANT: 1 foot = 12 inches
   public static class Measurement {
      
      private double inches = 0;
      
      public Measurement(double inches) {
      }
      
      public double getInches() {
         return 0.0;
      }
      
      public void setInches(double inches) {
      }
      
      public double getFeet() {
         return 0.0;
      }
   }
      
   
//....................................................................................................
//....................................................................................................
//.............................. :^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^: ..............................
//............................ :755YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY557: ............................
//...........................^?PP7:..................................:7PP?^ ..........................
//.........................^JP5!. ^JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ^ .75PJ^.........................
//..................... .~JP5!. ~YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY~ .!5PJ~. .....................
//................... .~YPY~  ~YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY~  ~YPY~. ...................
//................. .!YPY~ .!5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5!. ~YPY!. .................
//............... .!5PJ^ .75PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5!. ^JP5!. ...............
//............. :75PJ: .75PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP57. :?P57: .............
//........... :?PP?: :?5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5?: :?PP?: ...........
//..........^?PP7. ^JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJ^ .7PP?^ .........
//........^JP5!. ^JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJ^ .!5PJ^........
//......^JP5!  ~YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY~  !5PJ^......
//......YG7  ~YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY~  7GY......
//......YG~ :5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5: ~GY......
//......YG! :5PPPPPPPYJ?777?J5PPPPPYJJJJJJJJJJJJJJJ5PPPP5Y?777?YPPPPPPPYJJJJJJJJJYY5PPPPPP5: !GY......
//......YG! :5PPPPPJ^.       .~YPPG^               YPP57:       :75PPPP7           :!5PPPP5: !GY......
//......YG! :5PPPP?   .~!7!^   .JPP7^^^^^.   :^^^^~5P5^   :~!~:   ^5PPP7   :^^^^:.   :YPPP5: !GY......
//......YG! :5PPP5:  .YGPPPP7   ^PPPPPPPP^   JPPPPPP5^  .?PPPPPJ.  :PPP7   !PPPPPY^   !PPP5: !GY......
//......YG! :5PPPP^   ^?J55PPYYYYPPPPPPPP^   ?PPPPPPJ   ?PPPPPPG?   ?PP7   !PPPPPG!   ~PPP5: !GY......
//......YG! :5PPPP5^     .:^!?YPPPPPPPPPP^   ?PPPPPP!  .5PPPPPPP5:  ~GP7   ~555YJ7.   ?PPP5: !GY......
//......YG! :5PPPPPPJ~:.       ~YPPPPPPPP^   ?PPPPPP^  :5PPPPPPPP:  ^GP7    ...      !PPPP5: !GY......
//......YG! :5PPPPPPPP5YJ?!^.   .5PPPPPPP^   ?PPPPPP!  .5PPPPPPP5.  ~GP7   .::::::^!YPPPPP5: !GY......
//......YG! :5PPPJ~~^?GPPPPPP^   7GPPPPPP^   ?PPPPPPJ   7GPPPPPP?   ?PP7   !P55555PPPPPPPP5: !GY......
//......YG! :5PPPJ   .JPPPPP5^   ?PPPPPPP^   ?PPPPPP5^  .7PPPPP?.  :PPP7   !PPPPPPPPPPPPPP5: !GY......
//......YG! :5PPPP7    ^!!!~.   ^PPPPPPPP^   ?PPPPPPP5^   :~!~:   ^5PPP7   !PPPPPPPPPPPPPP5: !GY......
//......YG! :5PPPPPJ^.        :?PPPPPPPPP:   ?PPPPPPPPP7:       :75PPPP7   !PPPPPPPPPPPPPP5: !GY......
//......YG! :5PPPPPPP5J?777?JYPPPPPPPPPPPYJJJ5PPPPPPPPPPPYJ?77JYPPPPPPPYJJJYPPPPPPPPPPPPPP5: !GY......
//......YG~ :5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5: ~GY......
//......YG7  ~YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY~  7GY......
//......^JP5!  ~YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY~ .!5PJ^......
//........^JP5!. ^JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJ^ .75PJ^........
//......... ^?PP7. ^JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJ^ .7PP?^..........
//........... :?PP?: :?5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5?: :?PP?: ...........
//............. :75P?: .75PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP57. :?P57: .............
//............... .!5PJ^ .!5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5!. ^JP5!. ...............
//................. .!YPY~ .!5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5!. ~YPY!. .................
//................... .~YPY~  ~YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY~  ~YPY~. ...................
//..................... .~JP5!. ~YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY~ .!5PJ~. .....................
//.........................^JP57. ^JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ^ .75PJ^.........................
//.......................... ^?PP7:..................................:7PP?^ ..........................
//............................ :755YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY557: ............................
//.............................. :^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^: ..............................
//....................................................................................................
//....................................................................................................
   
   //DO NOT TOUCH OR EDIT THIS FUNCTION
   public static void main(String[] args) {
      
      Measurement[] m = new Measurement[10];
      double[] creationVal = {0.0, 10.0, 30.0, 45.5, 100.0, 12.0, 632.0, 99999.0, 632.0, 43.2};
      
      if (!mute) {
         System.out.println("Checking Measurement with 10 Tests");
         System.out.println("-------------------------------------------");
      }
      int casesPassed = 0;
      for (int i = 0; i < 10; i++) {
         boolean passed = false;
         m[i] = new Measurement(creationVal[i]);
         if (m[i].getInches() == creationVal[i]) {
            if (m[i].getFeet() == creationVal[i] / 12) {
               double rand = (Math.random() + 1) * 10;
               m[i].setInches(rand);
               if (m[i].getInches() == rand) {
                  if (m[i].getFeet() == rand / 12) {
                     casesPassed += 1;
                     passed = true;
                  }
               }
            }  
         }
         if (passed) {
            System.out.println("Case #" + (i + 1) + " Passed");
         } else {
            System.out.println("Case #" + (i + 1) + " Failed");
         }
      }
   }
}
